apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-hello
  template:
    metadata:
      labels:
        app: devops-hello
    spec:
      containers:
        - name: devops-hello
          image: devops-hello:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
